name: "Generate SQL"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "database/**"

jobs:
  generate-sql:
    name: Go test with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go mod tidy

      - name: Run command to generate SQL
        run: go run cmd/main.go --single --in database/v1/data --out database/v1/data/sql
